“Rails is the most well thought-out web development framework I’ve ever used.
And that’s in a decade of doing web applications for a living. I’ve built my
own frameworks, helped develop the Servlet API, and have created more than
a few web servers from scratch. Nobody has done it like this before.”
– James Duncan Davidson, Creator of Tomcat and Ant

“Ruby on Rails is a breakthrough in lowering the barriers of entry to programming.
Powerful web applications that formerly might have taken weeks or months
to develop can be produced in a matter of days.”
– Tim O’Reilly, Founder of O’Reilly Media

“It is impossible not to notice Ruby on Rails. It has had a huge effect both in
and outside the Ruby community... Rails has become a standard to which even
well-established tools are comparing themselves to.”
– Martin Fowler, Author of Refactoring, PoEAA, XP Explained

“What sets this framework apart from all of the others is the preference for
convention over configuration making applications easier
to develop and understand.”
– Sam Ruby, ASF board of directors

“Before Ruby on Rails, web programming required a lot of verbiage, steps and time.
Now, web designers and software engineers can develop a website
much faster and more simply, enabling them to be more productive
and effective in their work.”
– Bruce Perens, Open Source Luminary

“After researching the market, Ruby on Rails stood out as the best choice.
We have been very happy with that decision. We will continue
building on Rails and consider it a key business advantage.”
– Evan Williams, Creator of Blogger and ODEO

“Ruby on Rails is astounding. Using it is like watching a kung-fu movie,
where a dozen bad-ass frameworks prepare to beat up the little newcomer
only to be handed their asses in a variety of imaginative ways.”
– Nathan Torkington, O’Reilly Program Chair for OSCON

“Rails is the killer app for Ruby.”
– Yukihiro Matsumoto, Creator of Ruby
